package tema3;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel
 */
public class Form3 extends javax.swing.JFrame {
    Pila pila;
    JLabel dato[];
    int x, y;
    
    /**
     * Creates new form Form3
     */
    public Form3() {
        initComponents();
        setSize(400, 450);
        setLocationRelativeTo(this);
        
        pila = new Pila();
        dato = new JLabel[] {etiDato0, etiDato1, etiDato2, etiDato3, etiDato4, etiDato5};
        x = etiTope.getX();
        y = etiTope.getY();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        etiEncabezado = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        etiTope = new javax.swing.JLabel();
        etiDato0 = new javax.swing.JLabel();
        etiDato1 = new javax.swing.JLabel();
        etiDato2 = new javax.swing.JLabel();
        etiDato3 = new javax.swing.JLabel();
        etiDato4 = new javax.swing.JLabel();
        etiDato5 = new javax.swing.JLabel();
        btnMeter = new javax.swing.JButton();
        btnSacar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stack");
        getContentPane().setLayout(null);

        etiEncabezado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiEncabezado.setText("Pila: Vac�a");
        getContentPane().add(etiEncabezado);
        etiEncabezado.setBounds(8, 15, 77, 25);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(70, 150, 50, 10);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(231, 149, 11, 120);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(240, 150, 50, 10);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(128, 275, 104, 10);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(121, 149, 10, 120);

        etiTope.setText("<-- Tope");
        getContentPane().add(etiTope);
        etiTope.setBounds(248, 253, 41, 15);

        etiDato0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiDato0);
        etiDato0.setBounds(170, 250, 20, 20);

        etiDato1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiDato1);
        etiDato1.setBounds(170, 230, 20, 20);

        etiDato2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiDato2);
        etiDato2.setBounds(170, 210, 20, 20);

        etiDato3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiDato3);
        etiDato3.setBounds(170, 190, 20, 20);

        etiDato4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiDato4);
        etiDato4.setBounds(170, 170, 20, 20);

        etiDato5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiDato5);
        etiDato5.setBounds(170, 150, 20, 20);

        btnMeter.setText("Meter");
        btnMeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeterActionPerformed(evt);
            }
        });
        getContentPane().add(btnMeter);
        btnMeter.setBounds(46, 369, 61, 25);

        btnSacar.setText("Sacar");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSacar);
        btnSacar.setBounds(150, 369, 63, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeterActionPerformed
        // TODO add your handling code here:
        if (!pila.isFull()) {
            int ran = (int)(Math.random()*10);
            dato[pila.tope].setText("" + ran);
            pila.push(ran);
            y-=22;
            etiTope.setLocation(x, y);
        }
        else {
            JOptionPane.showMessageDialog(null, "La pila está llena");
        }
        
        if (pila.isFull()) {
            etiEncabezado.setText("Pila: llena");
        }
        else {
            if (pila.tope == 1) {
                etiEncabezado.setText("Pila: con " + (pila.tope) + " elemento");
            }
            else {
                etiEncabezado.setText("Pila: con " + (pila.tope) + " elementos");
            }
        }
    }//GEN-LAST:event_btnMeterActionPerformed

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        // TODO add your handling code here:
        if (!pila.isEmpty()) {
            dato[pila.tope-1].setText("");
            JOptionPane.showMessageDialog(null, "Dato eliminado: " + pila.pop());
            y+=22;
            etiTope.setLocation(x, y);
        }
        else {
            JOptionPane.showMessageDialog(null, "La pila está vacía");
        }
        
        if (pila.isEmpty()) {
            etiEncabezado.setText("Pila: Vacía");
        }
        else {
            if (pila.tope == 1) {
                etiEncabezado.setText("Pila: con " + (pila.tope) + " elemento");
            }
            else {
                etiEncabezado.setText("Pila: con " + (pila.tope) + " elementos");
            }
        }
    }//GEN-LAST:event_btnSacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMeter;
    private javax.swing.JButton btnSacar;
    private javax.swing.JLabel etiDato0;
    private javax.swing.JLabel etiDato1;
    private javax.swing.JLabel etiDato2;
    private javax.swing.JLabel etiDato3;
    private javax.swing.JLabel etiDato4;
    private javax.swing.JLabel etiDato5;
    private javax.swing.JLabel etiEncabezado;
    private javax.swing.JLabel etiTope;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
