package tema2;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Manuel
 */
public class CirculoDentroDeCuadrado extends javax.swing.JFrame {
    int tamaño = 600;
    
    /**
     * Creates new form CirculoDentroDeCuadrado
     */
    public CirculoDentroDeCuadrado() {
        initComponents();
        
        this.setTitle("Cuadrado 600 x 600");
        this.setSize(tamaño, tamaño);
        this.setLocationRelativeTo(this);
        this.getContentPane().setBackground(Color.black);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.setColor(Color.white);
        
        dibujar(g, 0, 0, tamaño, 4);
        
//        dibujar(g, 0, 0, tamaño / 3);
//        dibujar(g, 200, 0, tamaño / 3);
//        dibujar(g, 400, 0, tamaño / 3);
//        
//        dibujar(g, 0, 200, tamaño / 3);
//        dibujar(g, 0, 0, tamaño);
//        dibujar(g, 400, 200, tamaño / 3);
//        
//        dibujar(g, 0, 400, tamaño / 3);
//        dibujar(g, 200, 400, tamaño / 3);
//        dibujar(g, 400, 400, tamaño / 3);
    }
    
    public void dibujar(Graphics g, int x, int y, int tamaño, int c) {
        int tam = tamaño / 3;
        
        if (c > 0) {
            for (int i = 0; i < 9; i++) {
                if (i == 4) {
                    g.drawRect(x+tam, y+tam, tam, tam);
                }
                else {
//                    g.drawOval(x+tam*(i%3)+tam/3, y+tam*(i/3)+tam/3, tam/3, tam/3);
                    g.drawRect(x+tam/3 + tam*(i%3), y+tam/3 + tam*(i/3), tam/3, tam/3);
                    dibujar(g, x+tam*(i%3), y+tam*(i/3), tam, c-1);
                }
            }
        }
        
//        g.drawOval(x+tam/3 + (tam*0), y+tam/3 + (tam*0), tam/3, tam/3);
//        g.drawOval(x+tam/3 + (tam*1), y+tam/3 + (tam*0), tam/3, tam/3);
//        g.drawOval(x+tam/3 + (tam*2), y+tam/3 + (tam*0), tam/3, tam/3);
//        
//        g.drawOval(x+tam/3 + (tam*0), y+tam/3 + (tam*1), tam/3, tam/3);
//        g.drawOval(x+tam, y+tam, tam, tam);
//        g.drawOval(x+tam/3 + (tam*2), y+tam/3 + (tam*1), tam/3, tam/3);
//        
//        g.drawOval(x+tam/3 + (tam*0), y+tam/3 + (tam*2), tam/3, tam/3);
//        g.drawOval(x+tam/3 + (tam*1), y+tam/3 + (tam*2), tam/3, tam/3);
//        g.drawOval(x+tam/3 + (tam*2), y+tam/3 + (tam*2), tam/3, tam/3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CirculoDentroDeCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CirculoDentroDeCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CirculoDentroDeCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CirculoDentroDeCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CirculoDentroDeCuadrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
