package tema2;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Manuel
 */
public class CuadrosDesdeAdentro extends javax.swing.JFrame {
    int ancho, alto;
    int separacion;
    int xI, yI, xF, yF;
    int pausa;
    
    /**
     * Creates new form CuadrosDesdeAdentro
     */
    public CuadrosDesdeAdentro() {
        initComponents();
        
        this.setTitle("¿Que hago?");
        this.setSize(500, 500);
        this.setLocationRelativeTo(this);
        getContentPane().setBackground(Color.black);
        
        ancho = this.getWidth();
        alto = this.getHeight();
        separacion = 240;
        pausa = 100;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.setColor(Color.white);
        try {
            recursion(g, separacion);
        } catch (InterruptedException ex) {
            
        }
    }
    
    public void recursion(Graphics g, int separacion) throws InterruptedException {
        if (separacion > 50) {
            dibujar(g, separacion);
            Thread.sleep(pausa);
            recursion(g, separacion - 10);
        }
    }
    
    public void dibujar(Graphics g, int separacion) {
        ancho = getWidth();//para que el dibujo se
        alto = getHeight();//ajuste a la ventana
        
        xI = separacion; yI = separacion;
        xF = ancho - separacion; yF = yI;
        
        g.drawLine(xI, yI, xF, yF);
        
        xI = xF; yI = yF;
        xF = xI; yF = alto - separacion;
        
        g.drawLine(xI, yI, xF, yF);
        
        xI = xF; yI = yF;
        xF = separacion; yF = yI;
        
        g.drawLine(xI, yI, xF, yF);
        
        xI = xF; yI = yF;
        xF = xI; yF = separacion;
        
        g.drawLine(xI, yI, xF, yF);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuadrosDesdeAdentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuadrosDesdeAdentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuadrosDesdeAdentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuadrosDesdeAdentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuadrosDesdeAdentro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
