package tema2;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Manuel
 */
public class EspiralDeLineasRec extends javax.swing.JFrame {
    int ancho, alto;
    int sep;
    int xI, yI, xF, yF;
    int pausa;
    
    /**
     * Creates new form EspiralDeLineasRec
     */
    public EspiralDeLineasRec() {
        initComponents();
        
        this.setTitle("Espiral recursiva");
        this.setSize(500, 500);
        this.setLocationRelativeTo(this);
        this.getContentPane().setBackground(Color.black);
        
        ancho = this.getWidth();
        alto = this.getHeight();
        sep = 50;
        pausa = 50;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.setColor(Color.blue);
        
        recursion(g, sep);
    }
    
    public void recursion(Graphics g, int sep) {
        if (sep < 250) {
            
            try {
                dibujar(g, sep);
            } catch (InterruptedException ex) {}
            recursion(g, sep + 10);
        }
    }
    
    public void dibujar(Graphics g, int sep) throws InterruptedException {
        ancho = getWidth();
        alto = getHeight();
        
        xI = (sep - 10); yI = sep;
        xF = ancho - sep; yF = yI;
        
        g.drawLine(xI, yI, xF, yF);
        Thread.sleep(pausa);
        
        xI = xF; yI = yF;
        xF = xI; yF = alto - sep;
        
        g.drawLine(xI, yI, xF, yF);
        Thread.sleep(pausa);
        
        xI = xF; yI = yF;
        xF = sep; yF = yI;
        
        g.drawLine(xI, yI, xF, yF);
        Thread.sleep(pausa);
        
        xI = xF; yI = yF;
        xF = xI; yF = sep + 10;
        
        g.drawLine(xI, yI, xF, yF);
        Thread.sleep(pausa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspiralDeLineasRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspiralDeLineasRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspiralDeLineasRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspiralDeLineasRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EspiralDeLineasRec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
